# Generated by Django 4.0.4 on 2022-06-22 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('Access Bank', 'Access bank'), ('Access Bank (Diamond)', 'Access bank (Diamond)'), ('FCMB', 'FCMB'), ('Fidelity Bank', 'Fidelity bank'), ('First Bank', 'First bank'), ('GTB', 'GTB'), ('Heritage Bank', 'Heritage bank'), ('Keystone', 'Keystone'), ('Micro finance Bank', 'Micro finance bank'), ('Standard Chattered', 'Standard Chattered'), ('Union Bank', 'Union bank'), ('Zenith Bank', 'Zenith bank')], max_length=24)),
                ('bank_type', models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings'), ('Fixed deposit', 'Fixed deposit')], max_length=15)),
                ('account_number', models.PositiveIntegerField()),
                ('account_name', models.CharField(max_length=150)),
                ('bvn', models.PositiveIntegerField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
